[package]
name = "htmldocck"
version = "0.1.0"
description = "A test framework for rustdoc's HTML backend"
edition = "2021"

[dependencies]
getopts = "0.2"
regex = "1.8" # 1.8 to avoid memchr 2.6.0, as 2.5.0 is pinned in the workspace
shlex = "1.3.0"
unicode-width = "0.1.4"
